django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),  # new
    path("accounts/", include("django.contrib.auth.urls")),
    path("documentation/", include("docs.urls", namespace= "docs")), # documentation
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

docs/urls.py
from django.urls import path
from . import views

app_name = 'docs'

urlpatterns = [
    path("best practices/", views.Best_practices.as_view(), name= 'practices'),
    path("how it all works/", views.How_it_all_works.as_view(), name= 'works'),
    path("how to guides/", views.How_to_guides.as_view(), name= 'guides'),
    path("", views.Introduction.as_view(), name= 'intro'),
    path("technical reference/", views.Technical_reference.as_view(), name= 'ref'),
    path("tutorials/", views.Tutorials.as_view(), name= 'tut'),
    path("rate us/", views.Rate_us.as_view(), name= 'rate'),
]

docs/models.py
from django.db import models

# Create your models here.

class Review(models.Model):
    name = models.CharField(max_length= 50, blank= True, default= "No name")
    body = models.TextField()
    role = models.CharField(max_length= 200, blank= True, default= "No role")
    
    # for  ordering 
    created = models.DateTimeField(auto_now_add= True)
     
    """ 
    so you see newer comments first, which might actually be more 
    relevant from a designers ux point of view
    to anybody
    """
    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.body

docs/views.py
from django.shortcuts import render, get_list_or_404
from django.views.generic import ListView,TemplateView

from .models import Review

# Create your views here.

class Best_practices(TemplateView):
    template_name = 'docs/best_practices.html'


class How_it_all_works(TemplateView):
    template_name = 'docs/how_it_all_works.html'


class How_to_guides(TemplateView):
    template_name = 'docs/how_to_guides.html'


class Introduction(TemplateView):
    template_name = 'docs/introduction.html'


class Technical_reference(TemplateView):
    template_name = 'docs/technical_reference.html'


class Tutorials(TemplateView):
    template_name = 'docs/tutorials.html'

#form here !!!!
class Rate_us(ListView):
    model = Review
    template_name = 'docs/rate_us.html'
    context_object_name = 'review'

# since it has a form which returns the method post lets redefine that method
    def post(self, request):
        if request.method == 'POST':
            # getting the data
            m = Review()
            m.name = request.POST.get('name')
            m.role = request.POST.get('role')
            m.body = request.POST.get('comment')
            m.save()
            # so it still shows what it was given previously
            vi = get_list_or_404(Review)
        return render(request, 'docs/rate_us.html',
        {'review':vi }
        )

docs/templates/docs/best_practices.html
{% extends 'index.html' %}
{% block content %}
<div class="main-body">
    <div class="left-div">
      <ul>
        <li><a href="{% url 'docs:intro' %}">Introduction</a></li>
        <li><a href="{% url 'docs:tut' %}">Tutorials</a></li>
        <li><a href="{% url 'docs:guides' %}">How to Guide's</a></li>
        <li><a href="{% url 'docs:ref' %}">Technical reference</a></li>
        <li><a href="{% url 'docs:works' %}">How it all works</a></li>
        <li>Best practices</li>
        <li><a href="{% url 'docs:rate' %}">Rate us</a></li>
      </ul>
  </div>
  <!-- 
      sorry had to use inline style
      here to avoid creating a new
      page and also probably 
      because i'm lazy.
   -->
  <main style="width: 100%;padding-top: 50px;">
      <h2 style="padding-bottom: 30px;">BEST PRACTICES</h2>
      <p>
          Animations can greatly improve an interface's UX,
          but it's important to follow some guidelines to not overdo 
          it and deteriorate the user experience on your web-things.
          Following the following rules should provide a good start.
          <ul>
              <li>You should avoid animating an element just for the sake of it.</li>
              <li>Don't animate large elements</li>
              <li>Animating the <html> or <body> tags is possible, but you should avoid it</li>
              <li>You should avoid endless animations.
                  It will just distract your users and
                  might annoy a good slice of them</li>
          </ul>
      </p><br><br><br>
      <h2 >... Important to  note </h2>
      <p>
        You can’t use animations on inline elements, it might work on some
        browsers but eventually it won’t and it breaks some CSS
        specifications, but then there is a workaround just set the element
        you want to anim8’s
        <span style="color: #dcdf2f">display</span>:
        <span style="color: #c38651">inline-block</span>;
      </p><br><br><br><br>
       <!-- 
        django guys why does something smell like pagination here
       -->

      <!-- 
        and the link is like this so you can click anywhere on the div something of a UX law thingy
       -->
       <a href="{% url 'docs:rate' %}">
        <div class="next-page " style="gap: 800px;">
          <div class="title">
            <p style="font-size: 16px;color: #73777F;margin-bottom: -10px;">Next</p>
            <p style="font-size: 20px;color:#042947;font-weight: bolder;">Rate us</p>
          </div>
          <div class="arrow">
            {% load static %}
            <!-- i couldnt find the icon or probably did look hard enough but this works fine -->
            <img src="{% static 'docs/image-forward-icon.svg' %}" alt="next" />
          </div>
        </div>
      </a><br><br>
  </main>
  </div>
{% endblock content %}

docs/templates/docs/how_it_all_works.html
{% extends 'index.html' %} 
{% block content %} 
<div class="main-body">
    <div class="left-div">
      <ul>
          <li><a href="{% url 'docs:intro' %}">Introduction</a></li>
          <li><a href="{% url 'docs:tut' %}">Tutorials</a></li>
          <li><a href="{% url 'docs:guides' %}">How to Guide's</a></li>
          <li><a href="{% url 'docs:ref' %}">Technical reference</a></li>
          <li>How it all works</a></li>
          <li><a href="{% url 'docs:practices' %}">Best practices</a></li>
          <li><a href="{% url 'docs:rate' %}">Rate us</a></li>
        </ul>
    </div>
    <!-- 
        sorry had to use inline style
        here to avoid creating a new
        page and also probably 
        because i'm lazy.
     -->
    <main style="width: 100%;padding-top: 50px;">
        <h2>How it all works</h2>
        <p>
            We simply use the classes and add animations to these classes 
            in the css code which makes up the library 
            (simple CSS animations which are a lot easier than javascript
            animations so it's easier for you to edit).
            You could download the library to see the codes.
        </p><br><br><br><br>
         <!-- 
        django guys why does something smell like pagination here
       -->

      <!-- 
        and the link is like this so you can click anywhere on the div something of a UX law thingy
       -->
      <a href="{% url 'docs:practices' %}">
        <div class="next-page" style="gap: 750px;">
          <div class="title">
            <p style="font-size: 16px;color: #73777F;margin-bottom: -10px;">Next</p>
            <p style="font-size: 20px;color:#042947;font-weight: bolder;">Best practices</p>
          </div>
          <div class="arrow">
            {% load static %}
            <!-- i couldnt find the icon or probably did look hard enough but this works fine -->
            <img src="{% static 'docs/image-forward-icon.svg' %}" alt="next" />
          </div>
        </div>
      </a><br><br>
    </main>
  </div>
{% endblock content %}

docs/templates/docs/how_to_guides.html
{% extends 'index.html' %} 
{% block content %} 
<div class="main-body">
    <div class="left-div">
      <ul>
        <li><a href="{% url 'docs:intro' %}">Introduction</a></li>
        <li><a href="{% url 'docs:tut' %}">Tutorials</a></li>
        <li>How to Guide's</li>
        <li>
          <a href="{% url 'docs:ref' %}"
            >Technical reference</a
          >
        </li>
        <li>
          <a href="{% url 'docs:works' %}">How it all works</a>
        </li>
        </li>
        <li>
          <a href="{% url 'docs:practices' %}">Best practices</a>
        </li>
        <li><a href="{% url 'docs:rate' %}">Rate us</a></li>
      </ul>
    </div>
    <main>
      <h1>How to Guide's</h1>
      <h2>CHANGING DEFAULTS</h2>
      <p>You could simply go to the library and change stuff for example;</p>
      <p>This is how it looks in the library…</p>
      <br />
      <div class="code-snippet">
        ._repeat-2{ animation-iteration-count: 2; }
      </div>
      <br />
      <p>
        But then i could go and make it this and anywhere i put my _repeat-2
        it will repeat 3000 times (actually for this example one could have
        just used _repeat-infinite in the class list don't you think)
      </p>
      <br />
      <div class="code-snippet">
        ._repeat-2{ animation-iteration-count: 3000; }
      </div>
      <br />
      <p>
        Apart from changing the utility functions you can play around with the
        actual animations… BUT What if I make a mistake and break the library?
        You can always come back and re-download. We encourage you to keep
        breaking it, we even added notes, and learning, at least you could
        tell us what you’ve done and help others grow - like the true
        developers we know you are.
      </p>
      <br /><br /><br />
      <!-- 
        django guys why does something smell like pagination here
       -->

      <!-- 
        the link is like this so you can click anywhere on the div something of a UX law thingy
        and if you notice this div has a different gap so as to leave space for content
       -->
      <a href="{% url 'docs:ref' %}">
        <div class="next-page" style="gap: 290px">
          <div class="title">
            <p style="font-size: 16px; color: #73777f; margin-bottom: -10px">
              Next
            </p>
            <p style="font-size: 20px; color: #042947; font-weight: bolder">
              Technical reference
            </p>
          </div>
          <div class="arrow">
            {% load static %}
            <!-- i couldnt find the icon or probably did look hard enough but this works fine -->
            <img src="{% static 'docs/image-forward-icon.svg' %}" alt="next" />
          </div>
        </div>
      </a>
      <br /><br /><br />
    </main>
    <div class="right-div">
      <div class="page-content">
        <h3>CONTENTS</h3>
        <!-- the style was to make it look like its at 
       the center while still almost the same height 
       as the other content-small divs in other pages
   -->
        <div
          id="content-small"
          style="padding-bottom: 60px; padding-top: 60px"
        >
          <small>
            <ul id="content-small-first-ul">
              <!-- i used scroll to top in js cause my hands were tied i.e nothing above it same as
                 the place next leads to  and i left the #.. there so that it looks normal
                even though some users may not notice -->
              <li>
                <a href="#changing-defaults" onclick="window.scroll(0,0)"
                  >Changing defaults</a
                >
              </li>
            </ul>
          </small>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

docs/templates/docs/introduction.html
{% extends 'index.html' %} 
{% block content %} 
<div class="main-body">
    <div class="left-div">
      <ul>
        <li>Introduction</li>
        <li><a href="{% url 'docs:tut' %}">Tutorials</a></li>
        <li><a href="{% url 'docs:guides' %}">How to Guide's</a></li>
        <li><a href="{% url 'docs:ref' %}">Technical reference</a></li>
        <li><a href="{% url 'docs:works' %}">How it all works</a></li>
        <li><a href="{% url 'docs:practices' %}">Best practices</a></li>
        <li><a href="{% url 'docs:rate' %}">Rate us</a></li>
      </ul>
  </div>
  <main>
      <!-- 
          forgive my excessive use of br tag
          i did it because i want to re use
          the styling across the documentation
          and the margins for each p tag might be variable 
          and finally to save space that will have been wasted if 
          i use classes or tags and didnt use them
          accross all documentation pages.

          THANK YOU
       -->

       <!--
         i didnt put the id's at where it would have been because of the fact that the
         navbar is fixed and when i use the links to navigate it works like the navbar 
         is not on the same page but ontop the page and i dont want to use javascript
        i heard something like it putting more pressure on browsers and negatively impacting 
      loading time
      but from the id's name you will know what i want to lead to
      -->
    <h1>Introduction</h1>
    <p id="why-anim8">
      Anim8 is an open-source library filled with premade cross-browser CSS
      animations ready to take your project to the next level. Anim8 allows
      users to import or download web animations for faster development in
      normal language.
    </p>
    <br>
    <h3>WHY "Anim8"?</h3>
    <p>
      With anim8 you simply have the best at your fingertips with just a few
      words added to your class list - perfect for beginners, and those who
      simply want to do simple animations at break record timings. To name a
      few more:
      <ul>
          <li>
          Anim8 can be used as a cross-browser animation library in your online
          projects. Excellent for leading hints, home pages, sliders, and
          emphasis. They are compact files that function on desktops and can be
          resized without losing quality.
          </li>
          <li>
          One of the many methods to utilize Anim8 is to copy and paste the
          effect into your own CSS or to reference the stylesheet. Then, simply
          add the effect's class name to the element you want it to be applied
          to.
          </li>
          <li>It has a very modest file size.</li>
          <li>
          Use your favourite tools without jumping through endless hoops to
          ensure compatibility. Anim8 "just works". We worry about compatibility
          so that you don’t need to. Another headache is solved.
          </li>
          <li>
          Exposes animation elements and parameters to use as targeting elements
          to add interactivity and manipulate at run-time.
          </li>
          <br>
          <p id="before-you-continue">Read on to find out more.</p>
          <br><br>
      </ul>
      </p>
    <h3 id="how-this-documentation-is-arranged">Hold up! BEFORE YOU CONTINUE</h3>
    <p>Stuff you need to know</p><br>
    <h3>HOW THIS DOCUMENTATION IS ARRANGED</h3>
    <!-- 
      guys i noticed stuff i dont need those codes for < >
      in a p tag i just put it like that.
     -->
    <p>
      If you are new to this and want to get up and running in say 10min or so
      check the <a href="{% url 'docs:tut' %}">Tutorials</a>. 
      If you are interested in finding more information,
      especially about the animations we provide, our technical reference
      serves your purpose. If you feel the defaults aren’t your style and you
      want to change them do check the how-to guides. Lastly, if you’re
      curious and want to know how it all works the nuts and bolts and
      everything in between do check <a href="{% url 'docs:works' %}">How it all works</a>.
      <strong id="the-anim8-case">! Important</strong> - In all
      code snippets shown anything you see in between <...> is variable, just
      so you know. And now another important thing…
    </p><br>
    <h3>THE ANIM8 CASE</h3>
    <p>
      Since our purpose is to better the developer's life we have considered a case,
       how do we know which class belongs to which library
      (eg. bootstrap) assuming you want to use some other library so we use a special case 
      " _className".
    </p><br><br>
    <p>
      Now to the meat...
    </p><br><br><br>
    <!-- 
        django guys why does something smell like pagination here
       -->

      <!-- 
        the link is like this so you can click anywhere on the div something of a UX law thingy
        and if you notice this div has a different gap so as to leave space for content
       -->
       <a href="{% url 'docs:tut' %}">
        <div class="next-page" style="gap:380px;">
          <div class="title">
            <p style="font-size: 16px;color: #73777F;margin-bottom: -10px;">Next</p>
            <p style="font-size: 20px;color:#042947;font-weight: bolder;">Tutorials</p>
          </div>
          <div class="arrow">
            {% load static %}
            <!-- i couldnt find the icon or probably did look hard enough but this works fine -->
            <img src="{% static 'docs/image-forward-icon.svg' %}" alt="next" />
          </div>
        </div>
      </a>
      <br><br><br>
  </main>
  <div class="right-div">
    <div class="page-content">
      <h3>CONTENTS</h3>
      <div id="content-small">
          <small>
              <ul id="content-small-first-ul">
                  <li><a href="#why-anim8">Why Anim8</a></li>
                  <li><a href="#before-you-continue">Before you continue</a> 
                      <ul>
                          <li><a href="#how-this-documentation-is-arranged"> How this documentation is arranged</a></li>
                          <li><a href="#the-anim8-case"> Anim8 Case</a></li>
                      </ul>
                  </li>
              </ul> 
          </small>
      </div>
    </div>
  </div>
  </div>
{% endblock content %}

docs/templates/docs/rate_us.html
{% extends 'index.html' %} 
{% block content %}
<div class="main-body">
    <div class="left-div">
      <ul>
        <li><a href="{% url 'docs:intro' %}">Introduction</a></li>
        <li><a href="{% url 'docs:tut' %}">Tutorials</a></li>
        <li>
          <a href="{% url 'docs:guides' %}">How to Guide's</a>
        </li>
        <li>
          <a href="{% url 'docs:ref' %}"
            >Technical reference</a
          >
        </li>
        <li>
          <a href="{% url 'docs:works' %}">How it all works</a>
        </li>
        <li>
          <a href="{% url 'docs:practices' %}"> Best practices</a>
        </li>
        <li>Rate us</li>
      </ul>
    </div>
    <!-- i was too tired so i used inline styling SORRY HIGHLY ESTEEMED DEVS -->
    <main style="display: flex; width: 100%; padding-left: 0px">
      <style>
        h2 {
          font-weight: 600;
          font-size: 20px;
          line-height: 24px;
          letter-spacing: 0.005em;
          color: #1b1b1d;
        }
      </style>
      <div
        class="reviews"
        style="width: 75%; margin-left: 100px; padding-right: 50px"
      >
        <!-- sorry YEWANDE i broke your heart NO STAR RATINGS 🙂 -->
        <h1>Reviews</h1>
        <br />
        {% if not review %}
        <p style="color: #3990ec;text-align:center;"><strong>Be the first to talk, it'll help make anim8 better</strong></p>
        {% endif %}
        {% for i in review %}
        <hr />
        <br />
        <h2>
          {{ i.name }}
        </h2>
        <small>
          {{ i.role }}
        </small>
        <p>
          {{ i.body }}
        </p>
        <br />
        {% endfor %}
        <p style="text-align: right; font-size: 20px; font-weight: bolder">
          <span style="color: #0060a7; text-decoration-line: underline"
            >Rate us</span
          >👉🏿
        </p>
      </div>
      <div
        class="make-review"
        style="
          width: 25%;
          padding: 20px;
          border-left: 1px solid #afafaf;
          padding-left: 40px;
        "
      >
        <h2>Rate and Review</h2>
        <div>
          <!-- i still pitied yewande -->
          <small
            style="
              font-size: 12px;
              line-height: 16px;
              letter-spacing: 0.005em;
              color: #76777a;
            "
            >Ratings coming soon...</small
          >
        </div>
        <small
          style="
            font-weight: 600;
            font-size: 12px;
            line-height: 16px;
            letter-spacing: 0.005em;
            color: #76777a;
          "
          >Review</small
        >
        <form method="post" id="review-form">
          {% csrf_token %}
          <label for="name">name:</label>
          <input type="text" name="name" id="name" required />
          <hr />
          <!-- i used the &nbsp; so they will start from the same vertical axis -->
          <label for="role">role:&nbsp;&nbsp;&nbsp;</label>
          <input type="text" name="role" id="role" />
          <hr />
          <label for="comment">comment:</label><br />
          <textarea
            name="comment"
            id=""
            cols="30"
            rows="10"
            placeholder="Type here"
            required
          ></textarea>
          <button type="submit" id="review-publish">Publish</button>
        </form>
      </div>
    </main>
  </div>
{% endblock content %}

docs/templates/docs/technical_reference.html
{% extends 'index.html' %}
{% block content %}
<div class="main-body">
    <div class="left-div">
      <ul>
        <li><a href="{% url 'docs:intro' %}">Introduction</a></li>
        <li><a href="{% url 'docs:tut' %}">Tutorials</a></li>
        <li>
          <a href="{% url 'docs:guides' %}">How to Guide's</a>
        </li>
        <li>Technical reference</li>
        <li>
          <a href="{% url 'docs:works' %}">How it all works</a>
        </li>
        <li>
          <a href="{% url 'docs:practices' %}">Best practices</a>
        </li>
        <li><a href="{% url 'docs:rate' %}">Rate us</a></li>
      </ul>
  </div>
  <main>
    <h1>Technical Reference</h1>
    <h3 id="our-complete-list-of-animations">OUR COMPLETE LIST OF ANIMATION CLASSES</h3>
    <p>You’d know what they do from their names, neat right?</p>
    <p>
      Actually we have <strong>two</strong> types of animations (
      corresponding with the different folders you'd see them in upon
      installation ) and they are;
    </p>
    <br />
    <h4>Basic animations</h4>
    <table class="utils">
      <tr>
        <td>_moveUp</td>
      </tr>
      <tr>
        <td>_moveDown</td>
      </tr>
      <tr>
        <td>_moveRight</td>
      </tr>
      <tr>
        <td>_moveLeft</td>
      </tr>
      <tr>
        <td>_blink</td>
      </tr>
      <tr>
        <td>_fade</td>
      </tr>
      <tr>
        <td>_bounce</td>
      </tr>
    </table>
    <br />
    <h4>Attention seekers</h4>
    <table class="utils">
      <tr>
        <td>_popOut</td>
      </tr>
      <tr>
        <td>_tada</td>
      </tr>
      <tr>
        <td>_changeBgColor</td>
      </tr>
      <tr>
        <td>_shakeSide</td>
      </tr>
      <tr>
        <td>_shakeUpDown</td>
      </tr>
    </table><br><br><br>
     <!-- 
        django guys why does something smell like pagination here
       -->

      <!-- 
        the link is like this so you can click anywhere on the div something of a UX law thingy
        and if you notice this div has a different gap so as to leave space for content
       -->
       <a href="{% url 'docs:works' %}">
        <div class="next-page" style="gap: 320px;">
          <div class="title">
            <p style="font-size: 16px;color: #73777F;margin-bottom: -10px;">Next</p>
            <p style="font-size: 20px;color:#042947;font-weight: bolder;">How it all works</p>
          </div>
          <div class="arrow">
            {% load static %}
            <!-- i couldnt find the icon or probably did look hard enough but this works fine -->
            <img src="{% static 'docs/image-forward-icon.svg' %}" alt="next" />
          </div>
        </div>
      </a>
      <br><br><br>
  </main>
  <div class="right-div">
    <div class="page-content">
      <h3>CONTENTS</h3>
      <!-- the style was to make it look like its at 
       the center while still almost the same height 
       as the other content-small divs in other pages
   -->
      <div id="content-small" style="padding-bottom: 60px; padding-top: 60px">
        <small>
          <ul id="content-small-first-ul">
            <li><a href="#our-complete-list-of-animations"  onclick="window.scroll(0,0)">Our complete list of animations</a></li>
          </ul>
        </small>
      </div>
    </div>
  </div>
  </div>
{% endblock content %}